FROM python:3.11-slim-buster

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 psycopg

# Install python packages
RUN pip install numpy==1.26.4 mlflow==2.14.2 boto3