services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8050:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=Test123
      - AWS_DEFAULT_REGION=us-east-1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4568/
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack
    restart: always
    ports:
      - "4568:4566"
    environment:
      - SERVICES=kinesis
