{
 "title": "MLOps Taxi Monitoring Dashboard",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-30T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Daily RMSE performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",rmse FROM dummy_metrics "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",prediction_drift FROM dummy_metrics;"
    }
   ]
  },
  {
   "title": "Num Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare Amount Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",fare_amt_q50 FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",share_missing_values FROM dummy_metrics "
    }
   ]
  },
  {
   "title": "Pearson Correlation with Fare Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\",pearson_corr_fare_amt FROM dummy_metrics "
    }
   ]
  }
 ]
}